### ISSUE TITLE
Mose's Pointers Pt1 - Finals

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/PSMPlugin#2]
You know what time it is. 

This time im going to do them one by one, so this is pt1.

These fields never get touched after being set,therefore they should be set as final and marked with a name all in caps (if also static). Setting something final tells the compiler that the variable will never change and therefore the compiler wont allocate a buffer size in ram for it, but instead the exact size. While JDK is smart enough to work these sort of things out, it wont do so with fields as 3rd party software may expect it to be reassignable, so we set fields as final.

[ ] - "prefix" in Values
[ ] - "markerSet" in BorderMarkers
[ ] - all collection based "sides" in BattleSession

My advice here would be to look at the suggestions from Intelij. On the right hand side of the code screen in intelij, red, yellow and grey blocks will appear, clicking on those blocks will take you to the code that can be improved. Pressing "cntr + enter" (I thinks that) will give you a human readable reason why its giving you that suggestion as well as one or many solutions to fix it

**Comment by ColonelKai** [comment]
fixed https://github.com/ColonelKai/PSMPlugin/commit/d58c04d32c9c24f1befb43ec2d168eb3667bb284

**Comment by mosemister** [comment]
Putting caps on the name is only if the field is also static
