### ISSUE TITLE
Mose's pointers pt2 - questionable code

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/PSMPlugin#3]
https://github.com/ColonelKai/PSMPlugin/blob/master/src/main/java/colonelkai/psmplugin/psmbattle/BattleUser.java

Will a battle user have its UUID changed? It seems odd to change the UUID instead of just creating a new object. I mean, its faster doing it your way, but there are better optimisations you can do.

**Comment by ColonelKai** [comment]
whoops, that was a misclick when generating setter/getters lol https://github.com/ColonelKai/PSMPlugin/commit/508a379fef5d5659baf7dbbcd6c58cd6f5300013

**Comment by mosemister** [comment]
Uuid should be final
