### ISSUE TITLE
Mose's pointers pt3 - I smell a crash

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/PSMPlugin#4]
https://github.com/ColonelKai/PSMPlugin/blob/e4a49c8a4f8b27ac9e9ab6960e635fb982b80140/src/main/java/colonelkai/psmplugin/PSMPlugin.java#L24

Here you are setting a field with the result of a method, the result of that method is the field you are attempting to set....

I would suggest using a true singleton (ill give you a class that easily makes true singletons). If you dont know a true singleton is a field that is set to null until you actually need it, when you need it it sets the field as whatever value you want, so when you next call it, its that value from before. Saves on boot time and resources (if you dont use it)

**Comment by ColonelKai** [comment]
whoops, used wrong function https://github.com/ColonelKai/PSMPlugin/commit/67c5e7002e444cad1930410a088a19d266513edf
