### ISSUE TITLE
Mose's Pointers Pt4 - Dependencies

### ISSUE THREAD

**Issue by mosemister** [ColonelKai/PSMPlugin#5]
https://github.com/ColonelKai/PSMPlugin/blob/master/src/main/resources/plugin.yml

Bukkit uses a priority system when launching plugins, if a plugin relies on another plugin, the other plugin will load first and the second plugin being loaded after. 

Bukkit (since 1.13) also has multiple class loaders and if you rely on another plugin, then you will be put in the same class loader as that other plugin as it increases reliability and speed.

Your plugin relies on Dynmap, hoeever there is no mention of that in the plugin.yml. This may cause you issues where you rely on dynmap before its loaded

**Comment by ColonelKai** [comment]
done https://github.com/ColonelKai/PSMPlugin/commit/310ec409d9f8a6b7f468c5fb3449e21ee0a842f6
